openapi: 3.0.0
info:
  title: EIS Object API
  version: 1.0.0
  description: API for managing real estate objects (BASIC SIMPLE VARIANT)

components:
  schemas:
    RealEstateObject:
      type: object
      properties:
        type:
          type: string
          enum: [sell, rent]
        category:
          type: string
          enum: [apartment, house, land, commercial, business, factory, other]
        estateAgent:
          type: string # ObjectId in MongoDB
        geoPosition:
          type: object
          properties:
            city:
              type: string
            street:
              type: string
            houseNumber:
              type: string
            isInfoHidden:
              type: boolean
            mapLink:
              type: string
        description:
          type: string
        price:
          type: number
        discount:
          type: number
        mortgage:
          type: boolean
        visibilityStatus:
          type: string
          enum: [active, sold, canceled, checking]
        videoLink:
          type: string
        hasSwap:
          type: boolean
        isCommercial:
          type: boolean
        plede:
          type: string
        documents:
          type: string
        roomCount:
          type: integer
        houseBuildingYear:
          type: integer
        houseSquare:
          type: number
        kitchenSquare:
          type: number
        countFloor:
          type: integer
        ceilingHeight:
          type: number
        toiletCount:
          type: integer
        houseCondition:
          type: string
          enum: [perfect, good, bad, free, build]
        houseWallMaterial:
          type: string
          enum:
            [
              brick,
              wood,
              gasSilicateBlock,
              cinderBlock,
              heatBlock,
              panel,
              monolith,
              saman,
              gasConcreteBlock,
              foamBlock,
            ]
        houseRoofMaterial:
          type: string
          enum:
            [tile, soft, metal, ondulin, metalTile, corrugatedSheetRoof, slate]
        furniture:
          type: string
          enum: [part, full, none]
        ethernet:
          type: string
          enum: [connected, toConnect, none]
        plotSquare:
          type: number
        hasBasement:
          type: boolean
        hasMansard:
          type: boolean
        houseType:
          type: string
          enum: [part, full, cottage]
        electricType:
          type: string
          enum: [part, full, none]
        heatingType:
          type: string
          enum: [central, gas, solid, liquid, none]
        gasType:
          type: string
          enum: [central, auto, canConnect, none]
        sewerType:
          type: string
          enum: [central, septic, canConnect, none]
        toiletType:
          type: string
          enum: [in, out]
        waterType:
          type: string
          enum: [central, borehole, canConnect, none]
        targetFloor:
          type: integer
        totalFloor:
          type: integer
        landSquare:
          type: number

paths:
  /catalog:
    get:
      summary: Получить отфильтрованный список всех объектов недвижимости
      parameters:
        - in: query
          name: city
          schema:
            type: string
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: houseWallMaterial
          schema:
            type: string
        - in: query
          name: houseCondition
          schema:
            type: string
        - in: query
          name: roomCount
          schema:
            type: integer
        - in: query
          name: priceStart
          schema:
            type: number
        - in: query
          name: priceEnd
          schema:
            type: number
        - in: query
          name: houseSquare
          schema:
            type: number
        - in: query
          name: kitchenSquare
          schema:
            type: number
        - in: query
          name: houseBuildingYear
          schema:
            type: integer
        - in: query
          name: mortgage
          schema:
            type: boolean
        - in: query
          name: hasSwap
          schema:
            type: boolean
      responses:
        "200":
          description: Отфильтрованный список объектов недвижимости
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RealEstateObject"

  /catalog/{id}:
    get:
      summary: Получить один экземпляр объекта недвижимости
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Экземпляр объекта недвижимости
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RealEstateObject"

  /catalog/create:
    post:
      summary: Создать новый экземпляр объекта недвижимости
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RealEstateObject"
      responses:
        "201":
          description: Экземпляр объекта недвижимости создан

  /catalog/{id}/delete:
    delete:
      summary: Удалить экземпляр объекта недвижимости
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Экземпляр объекта недвижимости удален

  /catalog/{id}/update:
    put:
      summary: Редактировать экземпляр объекта недвижимости
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RealEstateObject"
      responses:
        "200":
          description: Экземпляр объекта недвижимости обновлен
